### ISSUE TITLE
Chat option is not visible in demo app when "call with chat" variant is selected.

### ISSUE THREAD

**Issue by ashishgxzc** [Azure/communication-ui-library-android#760]
No Chat button is visible in app when "Call with Chat" variant is selected.  

Steps to reproduce:
https://github.com/Azure/communication-ui-library-android/tree/main/azure-communication-ui/demo-app#readme

Expected Behaviour:
A chat button to open chat of meeting link.

**Comment by ahammer** [comment]
Hello, thank you for reporting this issue. We are aware that the call-with-chat functionality is not working properly in the demo app, and we will temporarily remove the call-with-chat functionality from the demo app. We previously added the call-with-chat variant because we were spiking on a proof of concept to showcase a call with chat integration experience. We will be looking at some architectural/system improvements in upcoming quarters to put us in a better position to support call-with-chat functionality. 

We apologize for the inconvenience and confusion this may have caused you, and we appreciate your patience and feedback. Please feel free to try out the other features of the demo app, and let us know if you encounter any other problems or have any suggestions. Thank you for using the Azure Communication Services UI library.

Please request the feature using this form to help us prioritize this work in upcoming quarters.
[Azure Feedback](https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858)

**Comment by ashishgxzc** [comment]
Thank you for the reply.

I was also facing an issue while using chat thread id from meeting link in chat app.

My meeting link was 

```
https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDNjN2Y2MGItNmZlZS00ODJmLTkwZjItNDA2MmVhYWMwMDUz%40thread.v2/0?context=%7b%22Tid%22%3a%22b8dafba5-a1a6-47e0-8fc1-11082de7a083%22%2c%22Oid%22%3a%227a25dd4a-398e-4256-beed-c9ea27ef9976%22%7d
```

Chat thread Id from meeting link will be
```19:meeting_MDNjN2Y2MGItNmZlZS00ODJmLTkwZjItNDA2MmVhYWMwMDUz@thread.v2```

```
Status code 403, "{
  "CommunicationError": {
   "Code": "Forbidden",
   "Message": "The initiator doesn't have the permission to perform the requested operation.",
  "Details": []
   }
}"
```
It works fine in the web. 
Is there any ongoing issue related to this?

**Comment by jpeng-ms** [comment]
Hi @ashishgxzc,

Thanks for reaching out to us. When you mentioned that it works fine in the web, were you talking about the Call with Chat composite for the web UI library? For Chat Composite, we don't support Teams Interop unfortunately and this is the case for web UI library as well. 

This is due to the nature of Teams Interop where a chat thread has to be in a Teams call. And chat participant would not be able to perform any chat related actions until they are admitted to the call. Because of this, unfortunately you won't be able to join a Teams chat with Chat Composite alone and you would need to use Call with Chat Composite instead.

Currently Call with Chat composite is available for the web UI library only. To learn more about it, you can check out our documentations [here](https://azure.github.io/communication-ui-library/?path=/docs/composites-call-with-chat-basicexample--basic-example).

Let me know if you have any other questions.

John

**Comment by ahammer** [comment]
Hi @ashishgxzc,

I'll be closing this issue because as we've removed Call+Chat from the repository to avoid confusion.

Adam
